site_name: Timescape Nexus
site_url: https://jacoblindey.github.io/nexus
repo_url: https://github.com/JacobLindey/nexus
edit_uri: edit/main/docs/ 

site_description: ""
site_author: "Jacob Lindey"

theme:
    name: 'material'
    features:
      - navigation.tracking
      - navigation.sections
      - navigation.indexes
      - navigation.top
      - header.autohide

    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true
      toc_depth: 2-6

plugins:
  - search
  - tags:
      tags_file: tags.md
  - roamlinks 
  - mermaid2
  - categories

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 

nav:
  - Home: 'index.md'
  - Categories: 
    - Campaigns: 'categories/campaigns'
    - Characters: 'categories/characters'
  
